### ISSUE TITLE
Advanced Plugin Concepts: unclear lesson section Give Full Control of Elements

### ISSUE THREAD

**Issue by PDMackinnon** [jquery/learn.jquery.com#419] opened 2013-09-13 13:47 UTC
https://github.com/jquery/learn.jquery.com/blob/master/page/plugins/advanced-plugin-concepts.md#give-full-control-of-elements

> If your plugin creates elements to be used within the DOM, then it's a good idea to offer plugin users some way to access those elements. Sometimes this means  giving certain elements IDs or classes. But note that your plugin shouldn't rely on these hooks internally:

> A bad implementation:

Perhaps its just me, but I cannot figure what it is that is bad about the implementation that follows. Further, the rest of the section appears to talk up the overall technique. Overall then, I think the text "A bad implementation: " is a mistake, or otherwise should be clarified as why this is bad.

**Comment by arthurvr** [comment] 2015-01-03 12:09
Can somebody close this as duplicate of https://github.com/jquery/learn.jquery.com/issues/513? This one is older, I know, but there were more comments and a PR in there.

**Comment by arthurvr** [comment] 2015-01-03 12:15
Can somebody close this down as duplicate of https://github.com/jquery/learn.jquery.com/issues/513?

**Comment by agcolom** [comment] 2015-01-03 17:24
@PDMackinnon Thanks for reporting this. I'm closing this issue as suggested by @arthurvr as a duplicate of #513

**Closed by agcolom** 2015-01-03 17:24 UTC
