### ISSUE TITLE
Confusing first sentence of tutorial content

### ISSUE THREAD

**Issue by jhhoffmann** [jquery/learn.jquery.com#806] opened 2021-12-01 17:02 UTC
Visiting jquery.com I followed the links that I thought would give me an introduction to JQuery. These are the links I followed, in order:

1. https://jquery.com/
2. https://learn.jquery.com/about-jquery/how-jquery-works/
3. https://learn.jquery.com/about-jquery/additional-support/
4. https://learn.jquery.com/using-jquery-core/
5. https://learn.jquery.com/using-jquery-core/dollar-object-vs-function/

_How JQuery Works_ showed how to include `jquery.js` into your HTML file. OK, good setup. The subsequent links were visited by clicking the "next" links at the bottom each page. Then we get to the page `dollar-object-vs-function`. The first sentence of this page is:

> Until now, we've been dealing entirely with methods that are called on a jQuery object. For example:
> 
> $( "h1" ).remove();

"Until now" I have not dealt with with any JavaScript code, let alone "methods that are called on a jQuery object". This first page of tutorial content seems like it should be something like the 20th.

**Comment by wizmer** [comment] 2022-11-28 10:11
I came on Github to post this as well. As a new JQuery user, this first sentence got me bamboozled.

In addition to the sentence being confusing, I already had multiple interrogation while following the links mentionned by the author. Here was my thought process while going through the pages:

1. jquery.com: Great, I'm in the right place
2. how-jquery-works: Ah weird, the page is called "How jquery works" but the page is just about how to setup a working page for the rest of the tutorial. It does not explain at all "How jquery works".
3. additional-support: Let me "getting started", I don't need additonal support yet, I want to learn the rudiment about JQuery first. Maybe when I'll have learnt a few bits about jquery, I'll be interested by some additional content. But that seems to early.
4. using-jquery-core: All right, I'm about to start for real. Great ! That's gonna be cool !
5. dollar-object-vs-function: "Until now, we've been dealing...". Ok I'm so confused, let's find another tutorial.

All in all, it seems, the getting started should go straight to the point. "Getting started" should probably take at most 2 clicks. Probably the "how jquery works" page could have more content and should be me first informative page where things are really getting started and where the first concepts are being introduced.

**Comment by IdfbAn** [comment] 2023-01-26 10:41
Hi, [here's](https://github.com/jquery/learn.jquery.com/blob/main/page/about-jquery/how-jquery-works.md) the file that "How jQuery Works" is built from. It seems like the build or whatever is sorta broken. It gets to the middle of the first note and then it just stops.

**Comment by Krinkle** [comment] 2023-03-26 05:36
> Hi, [here's](https://github.com/jquery/learn.jquery.com/blob/main/page/about-jquery/how-jquery-works.md) the file that "How jQuery Works" is built from. It seems like the build or whatever is sorta broken. It gets to the middle of the first note and then it just stops.

Correct. This was later reported at https://github.com/jquery/learn.jquery.com/issues/813. I believe the issue is now fixed.

**Closed by Krinkle** 2023-03-26 05:36 UTC
Labels: Chapter: jquery-core
